apiVersion: v1
kind: Service
metadata:
  labels:
    run: mutating-webhook
  name: mutating-webhook
  namespace: webhook
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    run: mutating-webhook
  type: ClusterIP