---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: NSXT | Compile main.tf
      template: src=main.tf dest={{ install_dir }}

    - name: "NSXT | Run tf | tail -f {{ install_dir }}/tf_manager.log"
      shell: terraform init && terraform plan > tf_manager.log && terraform apply -auto-approve >> tf_manager.log
      args:
        chdir: "{{ install_dir }}"

    - name: NSXT | Tf Check status
      shell: cat /tmp/vm-template.log
      args: 
        chdir: "{{ install_dir }}"
      register: tf_status
    - debug: var=tf_status.stdout