apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000                        # default value is 0
preemptionPolicy: Never               # will not evict lower priority pods
globalDefault: false                  # is not the default priorityClass of the pods
description: "This priority class will not cause other pods to be preempted."
