---
- hosts: manager
  gather_facts: no
  tasks:
    - name: Manager | Provision vm
      vmware_guest:
        hostname: "{{ vsphere_vcenter }}"
        username: "{{ vsphere_user }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vsphere_datacenter }}"
        validate_certs: no
        folder: "{{ vsphere_folder }}"
        resource_pool: "{{ vsphere_resource_pool.split('/')[-1] }}"
        name: "{{ nested_env }}-manager"
        state: poweredon
        template: "{{ manager_template }}"
        guest_id: centos64Guest
        disk:
        - size_gb: 1000
          type: thin
          datastore: "{{ vsphere_datastore }}"
        hardware:
          memory_mb: 4096
          num_cpus: 2
          scsi: paravirtual
        networks:
        - name: "{{ vsphere_network }}"
          ip: "{{ manager_ip }}"
          netmask: "{{ netmask_long }}"
          gateway: "{{ gateway }}"
      delegate_to: localhost

    - name: Manager | Wait 600 seconds for target vm to become reachable/usable
      wait_for_connection:
    - setup:
    
    - include_role: name=bertvv.dnsmasq
    - include_role: name=geerlingguy.nfs
