---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
  # - name: Retrieve jenkins initialpassword
  #   shell: |
  #     ssh root@192.168.95.150 'docker exec -t {{ container }} "cat" "/var/jenkins_home/secrets/initialAdminPassword"'
  #   register: jk_password
  # - debug: var=jk_password.stdout
  - template:
      src: templates/job_config.xml
      dest: /tmp/job_config.xml

  - name: Create a jenkins job using basic authentication
    community.general.jenkins_job:
      config: "{{ lookup('file', '/tmp/job_config.xml') }}"
      name: "{{ job_name }}"
      password: "{{ jk_password }}"
      url: "http://{{ jenkins_host }}:8080"
      user: "{{ jk_user }}"