---
- name: Check readiness of pod
  shell: "oc get pod {{ pod_name }} -n {{ namespace }} -o jsonpath='{.status.phase}'"
  register: output
  untill: 'output.stdout != "Running"'
  retries: 5
  delay: 3


# Temp directory
- name: Create a temporary directory
  tempfile:
    state: directory
  register: tmp_dir

- name: Remove the temporary directory
  file:
    path: "{{ tmp_dir.path }}"
    state: absent

# Inline if
secure: "{{ 'True' if item.protocol == 'SSL' else 'False' }}"

# Ignore Failure/Error
failed_when: "nitro_ret.http_response_data.status >= 400 and nitro_ret.http_response_data.status != 404"

# Dynamic var lookup
var1: "{{ lookup('vars', item.machine_type + '64').stdout  }}"